### PR TITLE
Review of Microverse Trials Past Project PR

### PR DESCRIPTION
**Pull request by teke85**
**In this Project:**

- _I created an empty repo._

- _Copied code from (https://github.com/serialferris/Solomon-and-Sannidhya.git) which was completed during the Microverse Trials_ 

- _Created a new branch and added the copied code._ 

- _Opened a pull request_ 

- _Played the role of Code Reviewer:_

1.       by checking to see if [semantic HTML tags] were used.

2.       Checking to see if [HTML & CSS best practices] were applied.

3.       Added comments after reviewing the project as per the HTML Semantics tags, and HTML and CSS best practices

### CODE REVIEW

**Comment by teke85** [comment]
Hi @name , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 💪 
- Descriptive pull request
- the project is working well on my pc
- A very good attempt replicating the original survey website.


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me  @teke85 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by teke85** [comment]
- [ ] README file is missing. Always remember to include a README file in all your projects. It is important to fill your README file with information describing your project. Luckily, Microverse has provided us with the [README template](https://github.com/microverseinc/readme-template/blob/master/README.md) to use and edit it to include all the information about our project. I would highly suggest you use that template and add all the necessary information about this project.

**Comment by teke85** [comment]
- [ ] Kindly use [these linters](https://github.com/microverseinc/linters-config/tree/master/html-css) provided by Microverse and make sure they are set up correctly and they all pass with green checkmarks. Using linters helps eradicate errors and produce clean code.

**Comment by teke85** [comment]
- [ ] Kindly Submit commits regularly to keep track of changes made while you code.

**Review by KayLemba — APPROVED** [review]
# STATUS: APPROVED :green_circle: :clap: 

Hello  @teke85       , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

well-1

[OPTIONAL] Kindly add a screenshot to your README file showing your webpage user Interface. You can use extentions like fireshot to capturer the entire page.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by teke85** [comment]
@KayLemba Thank you very much for taking the time to review my task. To better understand your optional comment are you suggesting I add a screenshot of the landing page of the project which I reviewed? Kindly see the image I have attached below.
screencapture-file-C-Users-Teke-Desktop-Samuel-and-Sannidhya-master-Samuel-and-Sannidhya-master-index-html-2022-07-11-10_12_35

**Pull request merged**
